[project]
name = "pdf-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Gokul RS",email = "gokulrsofficial@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mkdocs-material (>=9.7.7,<10.0.0)"
]
